### ISSUE TITLE
process.cwd is not a function

### ISSUE THREAD

**Issue by tbranyen** [tbranyen/diffhtml#137]
```
TypeError: process.cwd is not a function 11:08 AM     at resolve (path.js:1142:25) 11:08 AM     at EventEmitter.defaultConfiguration (/app/node_modules/express/lib/application.js:115:21) 11:08 AM
```

Somehow we're messing up the global `process` object in Node environments.

**Comment by tbranyen** [comment]
Fixed in: https://github.com/tbranyen/diffhtml/pull/138
